
name: EdTestz
description: A new Flutter application for loops (Project X)

publish_to: "none" # Remove this line if you wish to publish to pub.dev



version: 1.1.0+2

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  provider: ^6.0.3
  injectable: ^2.1.0
  injectable_generator: ^2.1.2
  flutter_screenutil: ^5.5.3+2
  logger: ^1.1.0
  dio: ^4.0.6
  fluttertoast: ^8.0.9
  dartz: ^0.10.1
  url_launcher: ^6.1.5
  shared_preferences: ^2.0.15
  flutter_secure_storage: ^6.1.0
  flutter_svg: ^1.0.3
  syncfusion_flutter_charts: ^20.2.39
  pin_code_fields: ^7.4.0
  percent_indicator: ^4.2.1
  expandable: ^5.0.1
  webview_flutter: ^3.0.4
  # cached_network_image: ^3.2.1
  package_info_plus: ^3.0.2
  version: ^3.0.2
  curved_progress_bar: ^1.0.0+1
  firebase_auth: ^4.1.5
  firebase_core: ^2.3.0
  pretty_dio_logger: ^1.2.0-beta-1
  path_provider: ^2.0.11
  cached_network_image:
  firebase_messaging: ^14.1.3
  firebase_analytics: ^10.0.6
  flutter_local_notifications: ^12.0.4
  upgrader: ^5.0.0
  in_app_update: ^4.0.1
  ippo_pay: ^1.0.0
  firebase_storage: ^11.0.11
  flutter_inappwebview: ^5.7.2+3
#  flutter_share: ^2.0.0
  share_plus: ^6.3.1
  crypto: ^3.0.3
  uuid: ^3.0.7
  open_filex: ^4.3.2
  connectivity_plus: ^4.0.1
  expandable_bottom_sheet: ^1.1.1+1

dependency_overrides:
  firebase_core_platform_interface: ^4.5.2

dev_dependencies:
  build_runner:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  lint: ^2.0.1


flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/bgs/
    # - assets/images/auth/
    - assets/icons/logos/
    - assets/images/home/
    - assets/fonts/hurme/
    - assets/fonts/Hurme_Geometric_Sans_No_1/
    - assets/images/other/
    - assets/images/profile/
    - assets/images/profile/performance/
    - assets/images/profile/activity/
    - assets/icons/tests_page/
    - assets/images/welcome/
    - assets/docs/
    - assets/svg/

  fonts:
    - family: Hurme
      fonts:
        - asset: assets/fonts/hurme/hurme-Thin.otf
          weight: 100
        - asset: assets/fonts/hurme/hurme-ThinItalic.otf
          weight: 100
          style: italic
        - asset: assets/fonts/hurme/hurme-UltraLight.otf
          weight: 200
        - asset: assets/fonts/hurme/hurme-UltraLightItalic.otf
          weight: 200
          style: italic
        - asset: assets/fonts/hurme/hurme-Light.otf
          weight: 300
        - asset: assets/fonts/hurme/hurme-LightItalic.otf
          weight: 300
          style: italic
        - asset: assets/fonts/hurme/hurme-Regular.otf
          weight: 400
        - asset: assets/fonts/hurme/hurme-RegularItalic.otf
          weight: 400
          style: italic
        - asset: assets/fonts/hurme/hurme-Medium.otf
          weight: 500
        - asset: assets/fonts/hurme/hurme-MediumItalic.otf
          weight: 500
          style: italic
        - asset: assets/fonts/hurme/hurme-Semibold.otf
          weight: 600
        - asset: assets/fonts/hurme/hurme-SemiboldItalic.otf
          weight: 600
          style: italic
        - asset: assets/fonts/hurme/hurme-Bold.otf
          weight: 700
        - asset: assets/fonts/hurme/hurme-BoldItalic.otf
          weight: 700
          style: italic
        - asset: assets/fonts/hurme/hurme-Extrabold.otf
          weight: 800
        - asset: assets/fonts/hurme/hurme-ExtraboldItalic.otf
          weight: 800
          style: italic
        # - asset: assets/fonts/hurme/hurme-Heavy.otf
        #   weight: 900
        # - asset: assets/fonts/hurme/hurme-HeavyItalic.otf
        #   weight: 900
        #   style: italic

    - family: HGS
      fonts:
        - asset: assets/fonts/Hurme_Geometric_Sans_1/HurmeGeometricSans2_Thin.otf
          weight: 100
        - asset: assets/fonts/Hurme_Geometric_Sans_1/HurmeGeometricSans2_ThinItalic.otf
          weight: 100
          style: italic
        - asset: assets/fonts/Hurme_Geometric_Sans_1/HurmeGeometricSans2_Hairline.otf
          weight: 200
        - asset: assets/fonts/Hurme_Geometric_Sans_1/HurmeGeometricSans2_HairlineItalic.otf
          weight: 200
          style: italic
        - asset: assets/fonts/Hurme_Geometric_Sans_1/HurmeGeometricSans2_Light.otf
          weight: 300
        - asset: assets/fonts/Hurme_Geometric_Sans_1/HurmeGeometricSans2_LightItalic.otf
          weight: 300
          style: italic
        - asset: assets/fonts/Hurme_Geometric_Sans_1/HurmeGeometricSans2_Black.otf
          weight: 400
        - asset: assets/fonts/Hurme_Geometric_Sans_1/HurmeGeometricSans2_BlackItalic.otf
          weight: 400
          style: italic
        - asset: assets/fonts/Hurme_Geometric_Sans_1/HurmeGeometricSans2.otf
          weight: 500
        - asset: assets/fonts/Hurme_Geometric_Sans_1/HurmeGeometricSans2.otf
          weight: 500
          style: italic
        - asset: assets/fonts/Hurme_Geometric_Sans_1/HurmeGeometricSans2_SemiBold.otf
          weight: 600
        - asset: assets/fonts/Hurme_Geometric_Sans_1/HurmeGeometricSans2_SemiBoldItalic.otf
          weight: 600
          style: italic
        - asset: assets/fonts/Hurme_Geometric_Sans_1/HurmeGeometricSans2_Bold.otf
          weight: 700
        - asset: assets/fonts/Hurme_Geometric_Sans_1/HurmeGeometricSans2_BoldItalic.otf
          weight: 700
          style: italic

    - family: HGS_light
      fonts:
        - asset: assets/fonts/Hurme_Geometric_Sans_No_1/HurmeGeometricSans1_Light.otf
          weight: 400

    - family: HGS_semi
      fonts:
        - asset: assets/fonts/Hurme_Geometric_Sans_No_1/HurmeGeometricSans1_SemiBold.otf
          weight: 600
